// <auto-generated />
using System;
using AlfaPackalApi.Datos;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AlfaPackalApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231129182440_AgregarBaseD")]
    partial class AgregarBaseD
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AlfaPackalApi.Modelos.Doctor", b =>
                {
                    b.Property<int>("DoctorID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DoctorID"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Especialidad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UserID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DoctorID");

                    b.ToTable("Doctores");
                });

            modelBuilder.Entity("AlfaPackalApi.Modelos.Estudio", b =>
                {
                    b.Property<int>("EstudioID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EstudioID"));

                    b.Property<string>("AccessionNumber")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("BodyPartExamined")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DescripcionEstudio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DoctorID")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ListaID")
                        .HasColumnType("int");

                    b.Property<int>("Modality")
                        .HasMaxLength(2)
                        .HasColumnType("int");

                    b.Property<int?>("PacienteID")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<DateTime>("StudyDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("StudyInstanceUID")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("TiempoEstudio")
                        .HasColumnType("int");

                    b.HasKey("EstudioID");

                    b.HasIndex("AccessionNumber")
                        .HasDatabaseName("IX_Estudios_AccessionNumber");

                    b.HasIndex("DoctorID");

                    b.HasIndex("ListaID");

                    b.HasIndex("PacienteID");

                    b.HasIndex("StudyDate")
                        .HasDatabaseName("IX_Estudios_StudyDate");

                    b.ToTable("Estudios");
                });

            modelBuilder.Entity("AlfaPackalApi.Modelos.Imagen", b =>
                {
                    b.Property<int>("ImagenID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ImagenID"));

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageLocation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ImageNumber")
                        .HasColumnType("int");

                    b.Property<string>("SOPInstanceUID")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("SerieID")
                        .HasColumnType("int");

                    b.HasKey("ImagenID");

                    b.HasIndex("ImageNumber")
                        .HasDatabaseName("IX_Imagen_ImageNumber");

                    b.HasIndex("SOPInstanceUID")
                        .HasDatabaseName("IX_Imagen_SOPInstanceUID");

                    b.HasIndex("SerieID");

                    b.ToTable("Imagenes");
                });

            modelBuilder.Entity("AlfaPackalApi.Modelos.ListaDeTrabajo", b =>
                {
                    b.Property<int>("ListaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ListaID"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("datetime2");

                    b.HasKey("ListaID");

                    b.ToTable("ListasDeTrabajo");
                });

            modelBuilder.Entity("AlfaPackalApi.Modelos.Paciente", b =>
                {
                    b.Property<int>("PacienteID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PacienteID"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<int>("Genero")
                        .HasMaxLength(1)
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("PacienteID");

                    b.HasIndex("Nombre")
                        .HasDatabaseName("IX_Paciente_Nombre");

                    b.ToTable("Pacientes");
                });

            modelBuilder.Entity("AlfaPackalApi.Modelos.Serie", b =>
                {
                    b.Property<int>("SerieID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SerieID"));

                    b.Property<int?>("EstudioID")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("SeriesDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SeriesInstanceUID")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("SeriesNumber")
                        .HasColumnType("int");

                    b.HasKey("SerieID");

                    b.HasIndex("EstudioID");

                    b.HasIndex("SeriesInstanceUID")
                        .HasDatabaseName("IX_Serie_SeriesInstanceUID");

                    b.HasIndex("SeriesNumber")
                        .HasDatabaseName("IX_Serie_SeriesNumber");

                    b.ToTable("Series");
                });

            modelBuilder.Entity("AlfaPackalApi.Modelos.Estudio", b =>
                {
                    b.HasOne("AlfaPackalApi.Modelos.Doctor", "Doctor")
                        .WithMany("Estudios")
                        .HasForeignKey("DoctorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AlfaPackalApi.Modelos.ListaDeTrabajo", "ListaDeTrabajo")
                        .WithMany("Estudios")
                        .HasForeignKey("ListaID");

                    b.HasOne("AlfaPackalApi.Modelos.Paciente", "Paciente")
                        .WithMany("Estudios")
                        .HasForeignKey("PacienteID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("ListaDeTrabajo");

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("AlfaPackalApi.Modelos.Imagen", b =>
                {
                    b.HasOne("AlfaPackalApi.Modelos.Serie", "Serie")
                        .WithMany("Imagenes")
                        .HasForeignKey("SerieID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Serie");
                });

            modelBuilder.Entity("AlfaPackalApi.Modelos.Serie", b =>
                {
                    b.HasOne("AlfaPackalApi.Modelos.Estudio", "Estudio")
                        .WithMany("Series")
                        .HasForeignKey("EstudioID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estudio");
                });

            modelBuilder.Entity("AlfaPackalApi.Modelos.Doctor", b =>
                {
                    b.Navigation("Estudios");
                });

            modelBuilder.Entity("AlfaPackalApi.Modelos.Estudio", b =>
                {
                    b.Navigation("Series");
                });

            modelBuilder.Entity("AlfaPackalApi.Modelos.ListaDeTrabajo", b =>
                {
                    b.Navigation("Estudios");
                });

            modelBuilder.Entity("AlfaPackalApi.Modelos.Paciente", b =>
                {
                    b.Navigation("Estudios");
                });

            modelBuilder.Entity("AlfaPackalApi.Modelos.Serie", b =>
                {
                    b.Navigation("Imagenes");
                });
#pragma warning restore 612, 618
        }
    }
}
